### PR TITLE
Added csv_to_json

### PR DESCRIPTION
**Pull request by jp9573**

### CODE REVIEW

**Comment by jp9573** [comment]
Hello,

Can you please tell me why this MR is on hold? Are there any changes required from my end?

**Comment by Chalarangelo** [comment]
@jp9573 Probably not, we are trying to figure out some internal things before we can proceed with merging this.

**Comment by jp9573** [comment]
> @jp9573 Probably not, we are trying to figure out some internal things before we can proceed with merging this.

Okay, can you please add `hacktoberfest-accepted` label to it.

**Comment by jp9573** [comment]
Re-opening MR.

**Pull request closed without merging**
