### PR TITLE
Improved `all_unique` , `all_equal` and added new snippet `indices_of_occurrence`

### PR DESCRIPTION
**Pull request by gurukiran07**
Previous [`all_unique`](https://github.com/30-seconds/30-seconds-of-python/blob/master/snippets/all_unique.md) creates a set of all the elements in the list. Can be improved by adding short-circuiting logic to it.

`timeit` results for `lst` of size `60_000_000`
```python
In [5]: x = [1, 2, 3, 4, 5, 6]

In [11]: %timeit new_all_unique(x*10_000_000)
279 ms ± 3.68 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [12]: %timeit all_unique(x*10_000_000) # prev version
655 ms ± 11.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
---

Previous [`all_equal`](https://github.com/30-seconds/30-seconds-of-python/blob/master/snippets/all_equal.md) creates two copies of `lst` i.e `[1:]` and `[:-1]` and compares them element by element. Can be improved by using `set()` over `lst` and checking if it's length is `1` or not

`timeit` results for `lst` of size `60_000_000`
```python
In [19]: x = [1, 1, 1, 1, 1, 1]

In [21]: %timeit new_all_eqaul(x*10_000_000)
749 ms ± 8.41 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [23]: %timeit all_equal(x*10_000_000) # prev vesion
1.19 s ± 12 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
---

Added new snippet `indices_of_occurrence` which returns a list of indices of all the occurrences of an elements, if element not found returns empty list `[]`

### CODE REVIEW

**Comment by gurukiran07** [comment]
@Trinityyi @Chalarangelo I have a doubt regarding what metric is being used to measure the difficulty of a problem. I contribute on StackOverflow and I have seen one question that a lot of users ask (finding all indices of all the occurrences of a value). Checked the master there's no answer to this question. I can contribute but what difficulty should be tagged?

**Review by Trinityyi — APPROVED** [review]
Thanks for the contribution. I'll make any changes necessary and merge this.

**Comment by Chalarangelo** [comment]
Closing as this was resolved by cherrypicking the commits into master and making the necessary changes. (Still counts for Hacktoberfest if you are interested, as it was approved)

**Comment by gurukiran07** [comment]
@Chalarangelo I found this repo through hacktoberfest, I contribute to repos that interest me. I personally had an idea to create a repo called one-liners in python. I did not do this for the sake hackocterfest TBH. I intend to contribute in long term. 

>  this was resolved by cherrypicking

I was going through all the snippets provided, felt these could be improved, so made a PR.

`indices_of_occurences` is a valid question that's asked a lot of times in StackOverflow, take a look into the question. Already added `indices_of_occurence.md`, as this PR is closed, I don't mind someone contributing that valid question.

**Comment by Trinityyi** [comment]
@gurukiran07 Thanks, long-term contributions are always a good thing. The snippet for the indices was actually merged, but we renamed it to be more SEO-friendly (somehow indexes is more searched for than indices). Your commits are on the master branch (except for the short-circuit one which we didn't see as very useful, except for the performance improvement), but we made a small mistake cherry-picking instead of pushing them to the PR branch. So, everything is the same as the PR having been merged normally. 😅

**Comment by gurukiran07** [comment]
@Trinityyi No problem :) Next time I will create a separate branch for each PR. Is there a gitter channel for this repo? I can post questions that are frequently asked in StackOverflow( in `python` and `python3.x` tag) in gitter and if they seem valuable, can contribute to repo. For the proof of evidence that I'm active on StackOverflow (link to my account [`Ch3steR`](https://stackoverflow.com/users/12416453/ch3ster?tab=profile))

**Comment by Chalarangelo** [comment]
@gurukiran07 Unfortunately we do not have a gitter channel anymore. However, you can definitely open an issue with a list of ideas and we can verify which ones seems interesting, so you can PR them individually. :wink:

**Pull request closed without merging**
