### PR TITLE
Added 'is' to make palindrome more self-explanatory

### PR DESCRIPTION
**Pull request by weydaej**

### CODE REVIEW

**Review by Trinityyi — COMMENTED** [review]
Closing as the change doesn't add anything useful to the snippet and is a low effort change. Thanks.

**Comment by weydaej** [comment]
Okay, fair to not merge it but why make it invalid? I felt it was a good change since functions that return booleans typically start with "is".

**Comment by Chalarangelo** [comment]
Because changes to the API of methods (footprint, naming etc) must serve an actual purpose. Also, we invalidate PRs that should be excluded from future searches when we are looking for information, as they just clutter up the issue tracker. Cheers.

**Comment by weydaej** [comment]
Just for argument's sake, when looking at your list it seems that boolean functions all start with "is_" such as is_anagram, is_contained_in, is_divisible, is_even, is_odd and is_prime. The reason I felt is_palindrome would be a useful change is because of the "follow existing conventions as seen in other snippets" mentioned in your CONTRIBUTING.md.

contributing

**Pull request closed without merging**
