### PR TITLE
Add split_list

### PR DESCRIPTION
**Pull request by JonasAlfredsson**
This code comes from one of my [gists][1], but could probably be more
useful here where it might be easier to find.

[1]: https://gist.github.com/JonasAlfredsson/6e30169c5c69813651baf050dbfc7203

### CODE REVIEW

**Comment by JonasAlfredsson** [comment]
While the code is very simple to use, the math (i.e. `divmod`) is a bit more advanced, which is why I tried to be very detailed with what each variable does. If this is too verbose I am more than willing to try to shorten the bullet points even further, but then it might become a little bit too vague.

**Review by Trinityyi — APPROVED** [review]
Thanks for the contribution. I'll make any changes necessary and merge this.

**Comment by JonasAlfredsson** [comment]
Hi,

I saw that you made some really significant changes to the code before merging this, and the new solution is something completely different than the one I uploaded. My example solves a different problem than the one that is now merged.

Some examples with `l = [1, 2, 3, 4, 5, 6, 7]`

My old solution:
```py
split_list(l, 2) # [[1, 2, 3, 4], [5, 6, 7]]
split_list(l, 3) # [[1, 2, 3], [4, 5], [6, 7]]
split_list(l, 9) # [[1], [2], [3], [4], [5], [6], [7]]
```

The new solution:
```py
chunk_into_n(l, 2) # [[1, 2, 3, 4], [5, 6, 7]]
chunk_into_n(l, 3) # [[1, 2, 3], [4, 5, 6], [7]]
chunk_into_n(l, 9) # [[1], [2], [3], [4], [5], [6], [7], [], []]
```

If you look at my old solution you see that the sub-lists differ at most 1 element from each other in length. This is to be desirable in cases where you perhaps want to split the list out into different thread workers and have the load spread as evenly as possible.

Secondly, the new solution will add empty elements if you try to split it into more than `len(l)` elements, which is also not desirable behavior IMO. 


Would it be OK if I try to submit my old solution again, or is it something you deem not useful?

**Comment by Chalarangelo** [comment]
@JonasAlfredsson the merged solution is far more common and more useful in most cases and also mirrors the one in the JS repo. We'll just stick to that one, no need to submit a different one, as the original version had some really hard-to-explain and quite frankly unexpected behavior.

**Comment by JonasAlfredsson** [comment]
Thank you for your response. 
That sounds reasonable, I just wanted to make sure you were aware of the differences in behavior of the two solutions.

**Pull request merged**
