### PR TITLE
New Snippet - Merge Dicts By Adding Values For Common Keys

### PR DESCRIPTION
**Pull request by HighnessAtharva**
A Python function to merge two dictionaries and add the values for common keys present in original dictionary.

### CODE REVIEW

**Review by Trinityyi — CHANGES_REQUESTED** [review]
Thanks for contributing. While the idea is mostly solid, there are a bunch of issues with the snippet, mainly in terms of not following the guidelines provided. Please read them carefully and make any necessary changes.

Additionally, I think that a `combine_values` snippet should produce a list with the combined values per dictionary key (i.e. `'a': [100, 300]`) instead of a sum to be usable with more than one type of data (hint: you can use `defaultdict()` for that). Summing the values afterwards is very easily accomplished with [`map_values()`](https://www.30secondsofcode.org/python/s/map-values), which is already implemented.

Finally, if refactored correctly, the snippet can be applied to any number of dictionaries (i.e. `*dicts`).

**Review by HighnessAtharva — COMMENTED** [review]
Please merge and close this pull request if there are no further issues.

**Review by Chalarangelo — CHANGES_REQUESTED** [review]
Please re-read the previous code review and also read [the guidelines](https://github.com/30-seconds/30-seconds-of-python/blob/master/CONTRIBUTING.md) more carefully. Your snippet doesn't even correctly follow the [snippet template](https://github.com/30-seconds/30-seconds-of-python/blob/master/snippet-template.md).

**Comment by 30secondsofcode** [comment]
Closing due to inactivity.

**Pull request closed without merging**
